### ISSUE TITLE
Cumulative imputation links are incorrect for FIC

### ISSUE THREAD

**Issue by robertswh** [ONSdigital/monthly-business-survey-results#22]
The `imputation_group` column is created by looking for changes in three columns:
- `missing_value` which is `True` or `False` depending on a return or non-return
- `group`
- `reference`

This works for most cases, but not for FIC. 

The `imputation_group` column should look at `imputation_marker` for changes instead of `missing_value`. There is some pre-processing needed because we look for changes in numerical columns, not categorical. One solution could be to create a new column (e.g. `mapped_marker`) for mapping of markers to numbers, e.g. `mapping = {"r": 1, "c": 2, "fir": 3, "bir": 4, "fic": 5}` (exact numbers doesn't matter as long as they're unique), then the condition would be `(dataframe["mapped_marker"].diff(time_difference) != 0)`.

This condition would replace the following condition:
https://github.com/ONSdigital/monthly-business-survey-results/blob/d2e8a386284a3f59b50df09c20b053a5fe3a3548/src/cumulative_imputation_links.py#L49

**Comment by AntonZogk** [comment]
By using this condition    
` (dataframe['imputation_marker'].ne(dataframe['imputation_marker'].shift().bfill()).astype(int) != 0)`

fixed the issue for cummulative links , it returns the correct values. But still the imputed value afterwards is wrong.

**Comment by AntonZogk** [comment]
When calculating the FIC the `create_and_merge_imputation_values` function should point at `Imputed_value` instead of `constructed` since it has all the constructed values and we can't do the required forward fill

**Comment by AntonZogk** [comment]
https://github.com/ONSdigital/monthly-business-survey-results/blob/d2e8a386284a3f59b50df09c20b053a5fe3a3548/src/apply_imputation_link.py#L55-L88

The marker values of the above must match (case sensitive) these:

https://github.com/ONSdigital/monthly-business-survey-results/blob/d2e8a386284a3f59b50df09c20b053a5fe3a3548/src/imputation_flags.py#L120-L125
